### ISSUE TITLE
Misalignment issues between the RGB and Point Cloud

### ISSUE THREAD

**Issue by Tgaaly** [BlazingForests/realsense_camera#1]
We are facing misalignment issues between the RGB and Point Cloud that varies with depth. The closer the object is to the camera the more the misalignment happens. At about 40 to 50cm we see a good alignment. Any ideas how to remedy this?a

**Comment by BlazingForests** [comment]
You can visit https://github.com/BlazingForests/realsense_camera_tools/blob/master/README.md#qa

Maybe can help you.

thx

**Comment by BlazingForests** [comment]
Confirmed, it works.
