### ISSUE TITLE
ReadMe not complete to support Depth-Sensor-Controls via uvc

### ISSUE THREAD

**Issue by arne48** [BlazingForests/realsense_camera#11]
I don't want to make a pull request for this small issue.
Could you please add the dependency on this:
https://github.com/teknotus/depthview/tree/udev
to the ReadMe.
The program and the udev-rule in that branch of depthview are loading
the control definitions for the depth sensor of the F200 when it is plugged in.
Without this, the startup and the attempt to change the configuration via dynamic reconfigure
just leads to errors of not supported control codes. (e.g. Control 134217728 is not supported)
Thanks

**Comment by BlazingForests** [comment]
Ok, I got it.

thx

**Comment by arne48** [comment]
Great, thank you.
