### ISSUE TITLE
Storing point clouds

### ISSUE THREAD

**Issue by Isabelp** [BlazingForests/realsense_camera#2]
Hi,

I am trying to store the pointclouds using bag_to_pcd or pointcloud_to_pcd but with both I always get just one pointcloud, since the name does not change every time, the file is overwritten, and it has the name "0". The trouble is not with bag_to_pcd or pointcloud_to_pcd because I have tested them with another packages (pointclouds from an asus xtion pro and another package for realsense) and works fine.  Could you give me a hint how can I solve this issue?
Thanks in advance,
Isabel

**Comment by teknotus** [comment]
It looks like pointcloud_to_pcd uses this line to create the file name. 
ss << prefix_ << cloud->header.stamp << ".pcd";

realsense_camera is putting timestamps on the images like this.
depth_img.header.stamp = ros::Time::now();
rgb_img.header.stamp = ros::Time::now();

I didn't find similar code to put timestamps on the pointclouds. 

I think you will need to add
realsense_xyz_cloud2.header.stamp = ros::Time::now();
in pubRealSensePointsXYZCloudMsg()

and
realsense_xyzrgb_cloud2.header.stamp = ros::Time::now();
in pubRealSensePointsXYZRGBCloudMsg()

**Comment by Isabelp** [comment]
Thank you very much @teknotus, it works now!

**Comment by teknotus** [comment]
Glad I could help.
