### ISSUE TITLE
CV_YUV2BGR_YUYV Problem

### ISSUE THREAD

**Issue by Nikvand** [BlazingForests/realsense_camera#22]
| Camera Model | F200 | 
| Firmware Version | 2.60.0.0 | 
| Operating System & Version | Ubuntu 14.04 LTS |
| Kernel Version (Linux Only) | 4.4.0-040400 generic |

Hi All,

I am getting the following error. CV_YUV2BGR_YUYV is a constant that is defined to be 116 in opencv headers.

Any ideas what's missing?

/home/nima/catkin_ws/src/realsense_camera/src/realsense_camera.cpp: In function ‘void processRGBD()’:
/home/nima/catkin_ws/src/realsense_camera/src/realsense_camera.cpp:576:39: error: ‘CV_YUV2BGR_YUYV’ was not declared in this scope
  cv::cvtColor(rgb_frame_yuv,rgb_frame,CV_YUV2BGR_YUYV);
                                       ^
make[2]: **\* [realsense_camera/CMakeFiles/realsense_camera_node.dir/src/realsense_camera.cpp.o] Error 1
make[1]: **\* [realsense_camera/CMakeFiles/realsense_camera_node.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by Nikvand** [comment]
To anyone concerned, this was an opencv problem, I solved it by downgrading to 2.4.9 from 3.0

**Comment by BlazingForests** [comment]
:) thx
